/**
 * Generates CREATE TABLE SQL snapshots from the live TypeORM metadata of the
 * @ackplus/nest-auth entity bundle, in three dialects (postgres, mysql,
 * sqlite). Output is written to public/sql/<dialect>.sql and consumed by the
 * Database Setup page so the copy-paste SQL is always accurate.
 *
 * Run: pnpm --filter @ackplus/nest-auth-docs generate:sql
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const outDir = resolve(import.meta.dirname, '..', 'public', 'sql');

async function main() {
  mkdirSync(outDir, { recursive: true });

  // TODO: import NestAuthEntities from @ackplus/nest-auth and use the TypeORM
  // SchemaBuilder to emit CREATE TABLE SQL per dialect. Pseudo-code:
  //
  //   for (const dialect of ['postgres', 'mysql', 'sqlite']) {
  //     const ds = new DataSource({ type: dialect, entities: NestAuthEntities });
  //     await ds.initialize();
  //     const sqls = ds.driver.createSchemaBuilder().log();
  //     writeFileSync(`${outDir}/${dialect}.sql`, sqls.upQueries.join(';\n') + ';');
  //     await ds.destroy();
  //   }
  //
  // For each dialect we want: CREATE TABLE for all 14 entities, indexes,
  // foreign keys (with CASCADE on userId where applicable).

  for (const dialect of ['postgres', 'mysql', 'sqlite']) {
    writeFileSync(
      resolve(outDir, `${dialect}.sql`),
      `-- ${dialect} schema for @ackplus/nest-auth\n` +
        '-- Generated by apps/docs/scripts/build-sql-snapshots.ts\n' +
        '-- TODO: implement TypeORM SchemaBuilder export.\n',
    );
  }

  console.log(`SQL snapshots written to ${outDir}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
